### ISSUE TITLE
Installation with kadaprofile fails

### ISSUE THREAD

**Issue by back-2-95** [City-of-Turku/kada#20]
or succeeds but gives Fatal error (all features checked):

```
Fatal error: Class name must be a valid object or a string in /vagrant/current/sites/all/modules/contrib/feeds/plugins/FeedsPlugin.inc on line 59
```

Installation was done in the UI: http://local.kada.fi/install.php?profile=kadaprofile 

Most of the times, installation failed.

**Comment by back-2-95** [comment]
Also I get this on some site installs, and the installation is halted to that:

`SQLSTATE[HY000]: General error: 1364 Field 'plugin' doesn't have a default value`

**Comment by ZeiP** [comment]
Thanks for the feedback!

I think we've only been using Drush for site installation; that has usually worked fine. If you're having problems with that as well, let us know. I'll leave this issue open since obviously it'd be better if the UI installation worked properly too.
