### ISSUE TITLE
Build Drupal from the make fails

### ISSUE THREAD

**Issue by MMikael18** [City-of-Turku/kada#36]
When I run build.
$ ./build.sh new

Build fails to the next line. I haw my virtual machine where I haw installed other Drupal sites. But is there soma other dependence that I need?

Unable to download openlayers from https://github.com/openlayers/openlayers/releases/download/release-2.13.1/OpenLayers-2.13.1.zip.              [error]
** BUILD ERROR: 'Make failed - check your makefile'

**Comment by kekkis** [comment]
For example PR #35 adds the following fix for the OpenLayers library URL:
https://github.com/City-of-Turku/kada/pull/35/commits/0ae15d869826c9e27407f6fd3dc983f544633cc1#diff-a209c490e863f67bfd2fcf218a4bf1d2

**Comment by MMikael18** [comment]
I clone a fix_build and it loads openlayer but still fails after that. 

Unable to download openlayers from                                                                             [error]
https://github.com/openlayers/openlayers/releases/download/release-2.13.1/OpenLayers-2.13.1.zip.
** BUILD ERROR: 'Make failed - check your makefile'

**Comment by MMikael18** [comment]
I get build do after I update my Drush to 7.
